general_configs : 
  sdk_session_id: 
    dev: 73832146be4549788ff2e627c968bbb2
    uat: 16ba37d0994549a7a3fb1df72563e37c
    prod: 64ec92d6117247877965d152
  tracking_env: dev
  tracking_url: mlcoredevv2sql21test.azurewebsites.net


data_engineering_ft:
  datalake_configs:
    input_tables :
      source_1 : 
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table : heart_rates_conf
        primary_keys: index
    output_tables :
      output_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_ft
        primary_keys: index
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  is_scheduled : true
  batch_size : 5000
  cron_job_schedule: 0 */30 * ? * *

data_engineering_gt:
  datalake_configs:
    input_tables :
      source_1 : 
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table : heart_rates_conf
        primary_keys: index
    output_tables :
      output_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_gt
        primary_keys: index
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  is_scheduled : true
  batch_size : 5000
  cron_job_schedule: 0 */30 * ? * *

feature_pipelines_ft:
  datalake_configs:
    input_tables :
      input_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_ft
        primary_keys: index
    output_tables :
        output_1 :
          catalog_name : mlcore_dev
          schema : synth_heart_rate
          table: heart_rates_conf_featur_pipe_ft
          primary_keys: index
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  is_scheduled: false

feature_pipelines_gt:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_gt
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : mlcore_dev
          schema : synth_heart_rate
          table: heart_rates_conf_featur_pipe_gt
          primary_keys: index  
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  is_scheduled: false

train:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_ft
        primary_keys: index
      input_2 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_gt
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : mlcore_dev
          schema : synth_heart_rate
          table: trainoutput_heart_rates_prophet
          primary_keys: index
        output_2 :
          catalog_name : mlcore_dev
          schema : synth_heart_rate
          table: trainoutput_heart_rates_xgb
          primary_keys: index
  model_configs :
    registry_platform: databricks
    model_registry : mlflow
    unity_catalog : "yes"
    model_registry_params :
      catalog_name: mlcore_dev
      schema_name: synth_heart_rate
    model_params:      
      model_name: synth_heart_rate_mlflow
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  test_size : 0.2
  feature_columns:
    - epoch
    - name
    - age_group
    - gender
    - lifestyle
  date_column: 'date_time'
  target_columns:
    - avg_heart_rate
  horizon: 7
  frequency: 'D'
  is_scheduled: false

data_prep_deployment_ft:
  datalake_configs:
    input_tables :
      input_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_ft
        primary_keys: index
    output_tables :
        output_1 :
          catalog_name : mlcore_dev
          schema : anemia_c_uc_uc_db_0207_v1
          table: heart_rates_conf_dpd_ft
          primary_keys: index  
        # output_2 :
        #   catalog_name : mlcore_dev
        #   schema : anemia_c_uc_uc_db_0207_v1
        #   table: dpd_feature_table_task_log_anemia_c_uc_0207_v1
        #   primary_keys: index
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  is_scheduled: true
  batch_size: 5000
  cron_job_schedule: 0 */30 * ? * *

data_prep_deployment_gt:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_gt
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : mlcore_dev
          schema : synth_heart_rate
          table: heart_rates_conf_dpd_gt
          primary_keys: index  
        # output_2 :
        #   catalog_name : mlcore_dev
        #   schema : anemia_c_uc_uc_db_0207_v1
        #   table: dpd_ground_truth_table_task_log_anemia_c_uc_0207_v1
        #   primary_keys: index
  storage_configs :
    cloud_provider : databricks_uc
    params:
      metastore : null
      catalog_name : mlcore_dev
      schema_name : mlcore
      volume_name : mlcore_volume
  is_scheduled: true
  batch_size: 5000
  cron_job_schedule: 0 */30 * ? * *

inference:
  datalake_configs:
    input_tables : 
      input_1 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_featur_pipe_ft
        primary_keys: index
      input_2 :
        catalog_name : mlcore_dev
        schema : synth_heart_rate
        table: heart_rates_conf_featur_pipe_gt
        primary_keys: index
    output_tables : 
        output_1 :
          catalog_name : mlcore_dev
          schema : synth_heart_rate
          table: heart_rates_conf_inference
          primary_keys: index
        # output_2 :
        #   catalog_name : mlcore_dev
        #   schema : synth_heart_rate
        #   table: inference_task_log_anemia_c_uc_2806
        #   primary_keys: index
  model_configs :
    use_latest_version: true
  is_scheduled: true
  batch_size: 5000
  cron_job_schedule: 0 */30 * ? * *